### ISSUE TITLE
기획. 책상 사진을 이용해서 뭘 하는게 좋을까?

### ISSUE THREAD

**Issue by Myeongchan-Kim** [Kyoo32/NEXT_hiDEsk#1]
무엇을 하는 것이 재밌을까?

위키가 안되서 일단 이슈로 등록... ㅋㅋ

참고할만한 링크 :
1. http://desk.cmiscm.com/
- 제작자 김종민씨의 책상사진 공유 사이트. 
- '책상은 창의성이 시작되는 곳.'
- 개발기간 3달 개발인원 1명!!! 충격...
- 인터뷰 링크 : http://www.worldweb.co.kr/articles/articles_view.html?idno=14679
1. http://macdesks.com/
2. 외국 맥 사용자들이 자기 책상 자랑하는 사이트
3. 진짜 예쁜 사진들이 많다.. ㅠㅠ
4. '최고의 맥 주변기기는 책상'

3 http://iconosquare.com/tag/%EC%B1%85%EC%83%81%EC%82%AC%EC%A7%84
- 인스타그램 #책상사진 모음.
- 왜 사람들은 책상사진을 올릴까...

기타 :
- 모 재단에서 사람들끼리 책상사진 찍은것 맞추면서 노는게시글 : 
  http://isori.net/bbs/BbsView.asp?regno=666&bbsdiv=11&bbscate=1#livere_send  
- 자기 책상사진을 주기적으로 모으는 사람도 은근 있는듯
  http://www.phpschool.com/gnuboard4/bbs/board.php?bo_table=talkbox2&wr_id=1396240&sca=&sfl=wr_subject%7C%7Cwr_content&stx=99&sop=and

**Comment by Kyoo32** [comment]
오 엄청난 브레인스토밍이네여!!

**Comment by Myeongchan-Kim** [comment]
각자 하고 싶은 주제를 이슈로 등록 해서 각자 페이스북에 실험해보는 것으로 이건 마무리 하겠습니다.
